# Generated by Django 5.2.6 on 2025-10-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_options'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_owner',
            field=models.BooleanField(default=False, verbose_name='Является ли владельцем'),
        ),
    ]
