# Generated by Django 5.2.6 on 2025-10-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storages', to='companies.company', verbose_name='Склад компании')),
            ],
        ),
    ]
